name: Validate application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics \
          --builtins=screen --per-file-ignore='specs/**/*:E9,F63,F7,F82'

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --show-source --exit-zero --max-complexity=10 \
          --max-line-length=127 --statistics --per-file-ignore='specs/**/*:E9,F63,F7,F82'
    
    - name: Set up Docker Compose
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./docker-compose.yml"
      env:
        DB_USER: "postgres"
        DB_PASSWD: "postgres"
        DB_NAME: "hotel_test"
        DB_PORT: 15432

    - name: Install Node.js via nvm
      uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: node
        node-mirror: https://nodejs.org/download/v8-canary/

    - name: Test with pytest
      run: sh run_tests.sh
    

